services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    networks:
      proxy:
        ipv4_address: 172.21.0.2

  npm:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    ports:  # These ports are in format <host-port>:<container-port>
      - '80:80'    # Public HTTP Port
      - '443:443'  # Public HTTPS Port
      - '81:81'    # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    # Uncomment the next line if you uncomment anything in the section
    environment:
      # Uncomment this if you want to change the location of the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your hos
      DISABLE_IPV6: 'true'
    networks:
      proxy:
        ipv4_address: 172.21.0.3

  adguard:
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    volumes:
      - ./adguard/data:/opt/adguardhome/work/data
      - ./adguard/config:/opt/adguardhome/conf
    ports:
      - '3000:3000/tcp'   # admin panel
      - '53:53/tcp'       # plain DNS
      - '53:53/udp'       # plain DNS
#      - '67:67/udp'      # dhcp
#      - '68:68/tcp'      # dhcp
#      - '68:68/udp'      # dhcp
#      - '853:853/tcp'    # DNS-over-TLS
#      - '784:784/udp'    # DNS-over-QUIC
#      - '853:853/udp'    # DNS-over-QUIC
#      - '8853:8853/udp'  # DNS-over-QUIC
#      - '5443:5443/tcp'  # DNSCrypt
#      - '5443:5443/udp'  # DNSCrypt
    networks:
      proxy:
        ipv4_address: 172.21.0.4
      vpn:
        ipv4_address: 10.8.1.90

  wireguard:
    container_name: wireguard
    image: ghcr.io/wg-easy/wg-easy
    restart: unless-stopped
    volumes:
      - ./wireguard/data:/etc/wireguard
    ports:
      - "51820:51820/udp"   # VPN
      - "51821:51821/tcp".  # Web UI
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      # Change Language: (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      
      # ⚠️ Required: Change this to your host's public address
      - WG_HOST=sub.domain.tld
      
      # ⚠️ Required: Change the Web UI Password:
      - PASSWORD=<insert your password here>
      
      # 💡 This is the AdGuard Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.90
      - WG_DEFAULT_ADDRESS=10.8.0.0
      - WG_DEFAULT_ADDRESS_RANGE=24

      # Optional:
      # - WG_PORT=51820
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 (0 # Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
    networks:
      proxy:
        ipv4_address: 172.21.0.5
      vpn:
        ipv4_address: 10.8.1.2

  ddns:
    container_name: ddns
    image: favonia/cloudflare-ddns:latest
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - CF_API_TOKEN=<insert cloudflare token>.  # pls adjust
      - DOMAINS=sub.domain.tld                   # pls adjust; a list of fully qualified domain names separated by commas
      - PROXIED=true                             # instructs Cloudflare to cache webpages on your machine and hide its actual IP addresses
      - TZ=Europe/Berlin
      - IP6_PROVIDER=none
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all
    read_only: true
    networks:
      proxy:
        ipv4_address: 172.21.0.6

  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - 3001:3000
#    environment:
#      - PUID=1000
#      - PGID=1000
    volumes:
      - ./homepage/config:/app/config
      - ./homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
      - /media:/media # (optional) for external storage stats when mounted in /media
    networks:
      proxy:
        ipv4_address: 172.21.0.10

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_HTTP_API_TOKEN=NiJKNDiJLUUKWPxzot6B48fVuDwUbM9g
      - WATCHTOWER_HTTP_API_METRICS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
    networks:
      proxy:
        ipv4_address: 172.21.0.11


networks:

  proxy:
    name: proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
  vpn:
    name: vpn
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.1.0/24
